### PR TITLE
Add scroller to youtube playlist and cleanup, added header

### PR DESCRIPTION
**Pull request by duckietm**
You can set the text of the Youtube windows by changing the : ExternalTexts.json

Look for the :
"catalog.page.youtube_tvs":

### CODE REVIEW

**Comment by duckietm** [comment]
image

**Comment by dank074** [comment]
Can you make it so that it only scrolls this section: 
image

**Comment by duckietm** [comment]
Sure no problem 👍 
image

**Comment by duckietm** [comment]
@dank074 Done !

**Review by dank074 — APPROVED** [review]
looks good

**Pull request merged**
